version: "3.9"

services:
  backend:
    image: tinkoff-edu-app:1.0.0
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      app:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://db/app-db'
      SPRING_DATASOURCE_USERNAME: app-db-admin
      SPRING_DATASOURCE_PASSWORD: mysecretpassword

  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    networks:
      app:
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: app-db-admin
      POSTGRES_PASSWORD: mysecretpassword

networks:
  app:
